CRUDExample/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;

using ServiceContracts;

namespace CRUDExample.Controllers;

[Route("[controller]")]
public class CountriesController : Controller
{
    private readonly ICountriesService _countriesService;

    public CountriesController(ICountriesService countriesService)
    {
        _countriesService = countriesService;
    }


    [Route("UploadFromExcel")]
    public IActionResult UploadFromExcel()
    {
        return View();
    }


    [HttpPost]
    [Route("UploadFromExcel")]
    public async Task<IActionResult> UploadFromExcel(IFormFile excelFile)
    {
        if (excelFile == null || excelFile.Length == 0)
        {
            ViewBag.ErrorMessage = "Please select an xlsx file";
            return View();
        }

        if (!Path.GetExtension(excelFile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
        {
            ViewBag.ErrorMessage = "Unsupported file. 'xlsx' file is expected";
            return View();
        }

        int countriesCountInserted = await _countriesService.UploadCountriesFromExcelFile(excelFile);

        ViewBag.Message = $"{countriesCountInserted} Countries Uploaded";
        return View();
    }
}

CRUDExample/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Rotativa.AspNetCore;

using ServiceContracts;
using ServiceContracts.DTO;
using ServiceContracts.Enums;

namespace CRUDExample.Controllers;

[Route("[controller]")]
public class PersonsController : Controller
{
    //private fields
    private readonly IPersonsService _personsService;
    private readonly ICountriesService _countriesService;

    //constructor
    public PersonsController(IPersonsService personsService, ICountriesService countriesService)
    {
        _personsService = personsService;
        _countriesService = countriesService;
    }

    //Url: persons/index
    [Route("[action]")]
    [Route("/")]
    public async Task<IActionResult> Index(string searchBy, string? searchString,
        string sortBy = nameof(PersonResponse.PersonName), SortOrderOptions sortOrder = SortOrderOptions.ASC)
    {
        //Search
        ViewBag.SearchFields = new Dictionary<string, string>()
        {
            { nameof(PersonResponse.PersonName), "Person Name" },
            { nameof(PersonResponse.Email), "Email" },
            { nameof(PersonResponse.DateOfBirth), "Date of Birth" },
            { nameof(PersonResponse.Gender), "Gender" },
            { nameof(PersonResponse.CountryID), "Country" },
            { nameof(PersonResponse.Address), "Address" }
        };


        List<PersonResponse> persons = await _personsService.GetFilteredPersons(searchBy, searchString);
        ViewBag.CurrentSearchBy = searchBy;
        ViewBag.CurrentSearchString = searchString;

        //Sort
        List<PersonResponse> sortedPersons = await _personsService.GetSortedPersons(persons, sortBy, sortOrder);
        ViewBag.CurrentSortBy = sortBy;
        ViewBag.CurrentSortOrder = sortOrder.ToString();

        return View(sortedPersons); //Views/Persons/Index.cshtml
    }


    //Executes when the user clicks on "Create Person" hyperlink (while opening the create view)
    //Url: persons/create
    [Route("[action]")]
    [HttpGet]
    public async Task<IActionResult> Create()
    {
        List<CountryResponse> countries = await _countriesService.GetAllCountries();
        ViewBag.Countries = countries.Select(temp =>
            new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() }
        );

        //new SelectListItem() { Text="Harsha", Value="1" }
        //<option value="1">Harsha</option>
        return View();
    }


    [HttpPost]
    //Url: persons/create
    [Route("[action]")]
    public async Task<IActionResult> Create(PersonAddRequest personAddRequest)
    {
        if (!ModelState.IsValid)
        {
            List<CountryResponse> countries = await _countriesService.GetAllCountries();
            ViewBag.Countries = countries.Select(temp =>
                new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() });

            ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
            return View(personAddRequest);
        }

        //call the service method
        PersonResponse personResponse = await _personsService.AddPerson(personAddRequest);

        //navigate to Index() action method (it makes another get request to "persons/index"
        return RedirectToAction("Index", "Persons");
    }

    [HttpGet]
    [Route("[action]/{personID}")] //Eg: /persons/edit/1
    public async Task<IActionResult> Edit(Guid personID)
    {
        PersonResponse? personResponse = await _personsService.GetPersonByPersonID(personID);
        if (personResponse == null)
        {
            return RedirectToAction("Index");
        }

        PersonUpdateRequest personUpdateRequest = personResponse.ToPersonUpdateRequest();

        List<CountryResponse> countries = await _countriesService.GetAllCountries();
        ViewBag.Countries = countries.Select(temp =>
            new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() });

        return View(personUpdateRequest);
    }


    [HttpPost]
    [Route("[action]/{personID}")]
    public async Task<IActionResult> Edit(PersonUpdateRequest personUpdateRequest)
    {
        PersonResponse? personResponse = await _personsService.GetPersonByPersonID(personUpdateRequest.PersonID);

        if (personResponse == null)
        {
            return RedirectToAction("Index");
        }

        if (ModelState.IsValid)
        {
            PersonResponse updatedPerson = await _personsService.UpdatePerson(personUpdateRequest);
            return RedirectToAction("Index");
        }
        else
        {
            List<CountryResponse> countries = await _countriesService.GetAllCountries();
            ViewBag.Countries = countries.Select(temp =>
                new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() });

            ViewBag.Errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
            return View(personResponse.ToPersonUpdateRequest());
        }
    }


    [HttpGet]
    [Route("[action]/{personID}")]
    public async Task<IActionResult> Delete(Guid? personID)
    {
        PersonResponse? personResponse = await _personsService.GetPersonByPersonID(personID);
        if (personResponse == null)
            return RedirectToAction("Index");

        return View(personResponse);
    }

    [HttpPost]
    [Route("[action]/{personID}")]
    public async Task<IActionResult> Delete(PersonUpdateRequest personUpdateResult)
    {
        PersonResponse? personResponse = await _personsService.GetPersonByPersonID(personUpdateResult.PersonID);
        if (personResponse == null)
            return RedirectToAction("Index");

        await _personsService.DeletePerson(personUpdateResult.PersonID);
        return RedirectToAction("Index");
    }


    [Route("PersonsPDF")]
    public async Task<IActionResult> PersonsPDF()
    {
        //Get list of persons
        List<PersonResponse> persons = await _personsService.GetAllPersons();

        //Return view as pdf
        return new ViewAsPdf("PersonsPDF", persons, ViewData)
        {
            PageMargins =
                new Rotativa.AspNetCore.Options.Margins() { Top = 20, Right = 20, Bottom = 20, Left = 20 },
            PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
        };
    }


    [Route("PersonsCSV")]
    public async Task<IActionResult> PersonsCSV()
    {
        MemoryStream memoryStream = await _personsService.GetPersonsCSV();
        return File(memoryStream, "application/octet-stream", "persons.csv");
    }


    [Route("PersonsExcel")]
    public async Task<IActionResult> PersonsExcel()
    {
        MemoryStream memoryStream = await _personsService.GetPersonsExcel();
        return File(memoryStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "persons.xlsx");
    }
}

CRUDExample/Views/Countries/UploadFromExcel.cshtml
@{
    ViewBag.Title = "Upload Countries from Excel";
}

<h2>Upload Countries from Excel</h2>
<div class="w-50">
    <form asp-action="UploadFromExcel" asp-controller="Countries" method="post" enctype="multipart/form-data">

        @* ExcelFile *@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt">Choose an xlsx file</label>
            </div>
            <div class="flex-1">
                <input type="file" name="excelFile" class="form-input"/>
                <div class="text-red">@ViewBag.ErrorMessage</div>
                <div class="text-green">@ViewBag.Message</div>
            </div>
        </div>

        <div class="form-field flex">
            <div class="w-25"></div>
            <div class="flex-1">
                <button type="submit" class="button button-green-back">Upload</button>
            </div>
        </div>

    </form>

</div>

CRUDExample/Views/Persons/Create.cshtml
@model PersonAddRequest

@{
    ViewBag.Title = "Create Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
<h2>Create Person</h2>

<div class="center-box">
    <form asp-controller="Persons" asp-action="Create" method="post">

        @*PersonName*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input"/>
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>


        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label pt">Email</label>
            </div>
            <div class="flex-1">
                <input asp-for="Email" class="form-input"/>
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>

        @*DateOfBirth*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="DateOfBirth" class="form-label pt">Date of Birth</label>
            </div>
            <div class="flex-1">
                <input type="date" asp-for="DateOfBirth" class="form-input"/>
                <span asp-validation-for="DateOfBirth" class="text-red"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label">Gender</label>
            </div>
            <div class="flex-1">
                @{
                    string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
                }
                @foreach (string gender in genders)
                {
                    <input type="radio" asp-for="Gender" value="@gender" id="@gender"/>
                    <label for="@gender">@gender</label>
                }
                <span asp-validation-for="Gender" class="text-red"></span>
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label" asp-for="CountryID">Country</label>
            </div>
            <div class="flex-1">
                <select asp-for="CountryID" class="form-input" asp-items="@ViewBag.Countries">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="CountryID" class="text-red"></span>
            </div>
        </div>


        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Address" class="form-label pt">Address</label>
            </div>
            <div class="flex-1">
                <textarea asp-for="Address" class="form-input"></textarea>
                <span asp-validation-for="Address" class="text-red"></span>
            </div>
        </div>

        @*ReceiveNewsLetters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <input asp-for="ReceiveNewsLetters" value="true"/>
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
                <span asp-validation-for="ReceiveNewsLetters" class="text-red"></span>
            </div>
        </div>

        @*Submit*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-green-back">Create</button>

                <div asp-validation-summary="All" class="text-red"></div>

                @if (ViewBag.Errors != null)
                {
                    <div class="text-red ml">
                        <ul>
                            @foreach (string error in ViewBag.Errors)
                            {
                                <li class="ml">@error</li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>

    </form>
</div>

@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="~/jquery.validate.unobtrusive.min.js"></script>
}

CRUDExample/Views/Persons/Delete.cshtml
@model PersonResponse

@{
    ViewBag.Title = "Delete Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
<h2>Delete Person</h2>
<h3>Are you sure to delete this person?</h3>

<div class="center-box">
    <form asp-controller="Persons" asp-action="Delete" method="post">

        <input type="hidden" asp-for="PersonID"/>

        @*PersonName*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input" disabled="disabled"/>
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>


        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label pt">Email</label>
            </div>
            <div class="flex-1">
                <input asp-for="Email" class="form-input" disabled="disabled"/>
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>


        @*Submit*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-red-back">Delete</button>

                <div asp-validation-summary="All" class="text-red"></div>

                @if (ViewBag.Errors != null)
                {
                    <div class="text-red ml">
                        <ul>
                            @foreach (string error in ViewBag.Errors)
                            {
                                <li class="ml">@error</li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>

    </form>
</div>

CRUDExample/Views/Persons/Edit.cshtml
@model PersonUpdateRequest

@{
    ViewBag.Title = "Edit Person";
}

<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
<h2>Edit Person</h2>

<div class="center-box">
    <form asp-controller="Persons" asp-action="Edit" method="post">

        <input type="hidden" asp-for="PersonID"/>

        @*PersonName*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="PersonName" class="form-label pt">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input"/>
                <span asp-validation-for="PersonName" class="text-red"></span>
            </div>
        </div>


        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Email" class="form-label pt">Email</label>
            </div>
            <div class="flex-1">
                <input asp-for="Email" class="form-input"/>
                <span asp-validation-for="Email" class="text-red"></span>
            </div>
        </div>

        @*DateOfBirth*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="DateOfBirth" class="form-label pt">Date of Birth</label>
            </div>
            <div class="flex-1">
                <input type="date" asp-for="DateOfBirth" class="form-input"/>
                <span asp-validation-for="DateOfBirth" class="text-red"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label">Gender</label>
            </div>
            <div class="flex-1">
                @{
                    string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
                }
                @foreach (string gender in genders)
                {
                    <input type="radio" asp-for="Gender" value="@gender" id="@gender"/>
                    <label for="@gender">@gender</label>
                }
                <span asp-validation-for="Gender" class="text-red"></span>
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label" asp-for="CountryID">Country</label>
            </div>
            <div class="flex-1">
                <select asp-for="CountryID" class="form-input" asp-items="@ViewBag.Countries">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="CountryID" class="text-red"></span>
            </div>
        </div>


        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label asp-for="Address" class="form-label pt">Address</label>
            </div>
            <div class="flex-1">
                <textarea asp-for="Address" class="form-input"></textarea>
                <span asp-validation-for="Address" class="text-red"></span>
            </div>
        </div>

        @*ReceiveNewsLetters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <input asp-for="ReceiveNewsLetters" value="true"/>
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
                <span asp-validation-for="ReceiveNewsLetters" class="text-red"></span>
            </div>
        </div>

        @*Submit*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <button class="button button-green-back">Update</button>

                <div asp-validation-summary="All" class="text-red"></div>

                @if (ViewBag.Errors != null)
                {
                    <div class="text-red ml">
                        <ul>
                            @foreach (string error in ViewBag.Errors)
                            {
                                <li class="ml">@error</li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>

    </form>
</div>

@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="~/jquery.validate.unobtrusive.min.js"></script>
}

CRUDExample/Views/Persons/Index.cshtml
@model IEnumerable<PersonResponse>

@{
    ViewBag.Title = "Persons";
}
<form asp-controller="Persons" asp-action="Index" method="get">
    <h1>Persons</h1>

    <a asp-controller="Persons" asp-action="Create">Create Person</a>

    <a asp-controller="Persons" asp-action="PersonsPDF" class="ml">Download as PDF</a>

    <a asp-controller="Persons" asp-action="PersonsCSV" class="ml">Download as CSV</a>

    <a asp-controller="Persons" asp-action="PersonsExcel" class="ml">Download as Excel</a>

    <div class="box flex">
        <div class="flex-1">
            <select class="form-input" name="searchBy">
                @foreach (var field in ViewBag.SearchFields)
                {
                    if (field.Key == ViewBag.CurrentSearchBy)
                    {
                        <option value="@field.Key" selected="selected">@field.Value</option>
                    }
                    else
                    {
                        <option value="@field.Key">@field.Value</option>
                    }
                }
                @* Eg: searchBy=PersonName&searchString=abc *@
            </select>
        </div>

        <div class="flex-1">
            <input type="search" id="Search" class="form-input" placeholder="Search" name="searchString" value="@ViewBag.CurrentSearchString"/>
        </div>

        <div class="flex-1">
            <button class="button button-blue-back">Search</button>
            <a asp-controller="Persons" asp-action="Index" class="link-hover">Clear all</a>
        </div>
    </div>


    <table class="table w-100 mt">
        <thead>
        <tr>
            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.PersonName) },
                       { "DisplayName", "Person Name" },
                   })

            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.Email) },
                       { "DisplayName", "Email" },
                   })

            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.DateOfBirth) },
                       { "DisplayName", "Date of Birth" },
                   })

            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.Age) },
                       { "DisplayName", "Age" },
                   })

            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.Gender) },
                       { "DisplayName", "Gender" },
                   })

            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.Country) },
                       { "DisplayName", "Country" },
                   })

            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.Address) },
                       { "DisplayName", "Address" },
                   })

            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                   {
                       { "ColumnName", nameof(PersonResponse.ReceiveNewsLetters) },
                       { "DisplayName", "Receive News Letters" },
                   })

            <th>Options</th>

        </tr>
        </thead>
        <tbody>
        @foreach (PersonResponse person in Model)
        {
            <tr>
                <td style="width:15%">@person.PersonName</td>
                <td style="width:20%">@person.Email</td>
                <td style="width:13%">@person.DateOfBirth?.ToString("dd MMM yyyy")</td>
                <td style="width:9%">@person.Age</td>
                <td style="width:9%">@person.Gender</td>
                <td style="width:10%">@person.Country</td>
                <td style="width:15%">@person.Address</td>
                <td style="width:20%">@person.ReceiveNewsLetters</td>
                <td style="width:20%">
                    <a asp-controller="Persons" asp-action="Edit" asp-route-personID="@person.PersonID">Edit</a>
                    @* /Persons/Edit/1 *@

                    <a asp-controller="Persons" asp-action="Delete" asp-route-personID="@person.PersonID">Delete</a>
                    @* /Persons/Delete/1 *@
                </td>
            </tr>
        }
        <tr></tr>
        </tbody>

    </table>
</form>

CRUDExample/Views/Persons/PersonsPDF.cshtml
@model IEnumerable<PersonResponse>

@{
    Layout = null;
}

<link href="@("http://" + Context.Request.Host.ToString() + "/Stylesheet.css")" rel="stylesheet"/>
@* http://localhost:port/StyleSheet.css *@

<h1>Persons</h1>

<table class="table w-100 mt">
    <thead>
    <tr>
        <th>Person Name</th>
        <th>Email</th>
        <th>Date of Birth</th>
        <th>Age</th>
        <th>Gender</th>
        <th>Country</th>
        <th>Address</th>
        <th>Receive News Letters</th>
    </tr>
    </thead>
    <tbody>
    @foreach (PersonResponse person in Model)
    {
        <tr>
            <td style="width:15%">@person.PersonName</td>
            <td style="width:20%">@person.Email</td>
            <td style="width:13%">@person.DateOfBirth?.ToString("dd MMM yyyy")</td>
            <td style="width:9%">@person.Age</td>
            <td style="width:9%">@person.Gender</td>
            <td style="width:10%">@person.Country</td>
            <td style="width:15%">@person.Address</td>
            <td style="width:20%">@person.ReceiveNewsLetters</td>
        </tr>
    }
    </tbody>

</table>

CRUDExample/Views/Shared/_GridColumnHeader.cshtml
@if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderOptions.ASC.ToString())
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(nameof(SortOrderOptions.DESC))">@(ViewBag.DisplayName)</a>
        <i class="fa-solid fa-sort-up"></i>
    </th>
}
else if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderOptions.DESC.ToString())
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(nameof(SortOrderOptions.ASC))">@(ViewBag.DisplayName)</a>
        <i class="fa-solid fa-sort-down"></i>
    </th>
}
else
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(nameof(SortOrderOptions.ASC))">@ViewBag.DisplayName</a>
    </th>
}

CRUDExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    <link href="~/Stylesheet.css" rel="stylesheet"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer"/>

</head>
<body>
<div class="container">
    <div class="navbar">
        <div class="navbar-brand">
            <img src="~/logo.png" width="30px" asp-append-version="true"/>
        </div>
        <ul>
            <li>
                <a asp-controller="Persons" asp-action="Index">Persons</a>
                <a asp-controller="Countries" asp-action="UploadFromExcel">Upload Countries</a>
            </li>
        </ul>
    </div>

    <div class="page-content">
        @RenderBody()
    </div>
</div>

@RenderSection("scripts", required: false)
</body>
</html>